#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

echo "===> Installing top-level dependencies..."
cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  echo "==> Updating Homebrew..."
  brew update

  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies..."
    brew bundle
  }
fi

echo "===> Installing api dependencies..."
cd "api"

echo "==> Checking rbenv installation..."
if [[ ":$PATH:" == *":$HOME/.rbenv/shims:"* ]]; then
  echo "rbenv looks correctly installed."
else
  >&2 echo "rbenv isn't correctly installed! Run:"
  >&2 echo ""
  >&2 echo "  rbenv init"
  >&2 echo ""
  >&2 echo "then follow the directions. See https://github.com/rbenv/rbenv for more info."
  exit 1
fi

if [ -f ".ruby-version" ] && [ -z "$(rbenv version-name 2>/dev/null)" ]; then
  echo "==> Installing Ruby..."
  rbenv install --skip-existing
fi

which bundle >/dev/null 2>&1  || {
  gem install bundler
  rbenv rehash
}

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies..."
  bundle check >/dev/null 2>&1  || {
    # If this fails on pg gem install and you use Postgres.app,
    # see http://stackoverflow.com/a/20226895; TL;DR, do:
    # gem install pg -v '0.18.4' -- --with-pg-config=$(find /Applications -name pg_config)
    bundle install --quiet --without production
  }
fi

echo "===> Installing frontend dependencies..."
cd "../frontend"

which bower >/dev/null 2>&1  || {
  npm install -gq bower
}

which ember >/dev/null 2>&1  || {
  npm install -gq ember
}

echo "==> Installing ember app dependencies..."
npm i -q --no-optional
bower i
