#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

script/update

test -z "$RAILS_ENV" &&
  RAILS_ENV='development'

foreman start
